ECommercePlatform:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host:
    port: 
    database: 
    username: 
    password: 
  redis:
    host: 121.4.24.200
    port: 6379
    password: 123456
    database: 0
